"""Exact lattice symmetries defining the six-amplitude static ansatz.

The transformations act on periodic velocity fields by a signed coordinate
orthogonal map followed by a quarter-period translation.  They preserve the
static Navier--Stokes functional and their common fixed space in the canonical
64-real low-mode coordinates is precisely the six-amplitude ansatz.
"""

from __future__ import annotations

from fractions import Fraction
from functools import lru_cache
from itertools import permutations, product
from typing import Sequence

from .certify import QComplex, StaticLowModePolynomial, integer_polarizations
from .reduced_static import embed_reduced_static
from .reduced_competing import embed_competing


Matrix3 = tuple[tuple[int, int, int], tuple[int, int, int], tuple[int, int, int]]
Generator = tuple[Matrix3, tuple[int, int, int]]

IDENTITY_GENERATOR: Generator = (
    ((1, 0, 0), (0, 1, 0), (0, 0, 1)),
    (0, 0, 0),
)


# (Q, m) means v(x)=Q u(Q^T(x-tau)), tau=pi*m/2.  The phase convention in
# Fourier variables is v_hat(k)=Q u_hat(Q^T k) exp(-i(Q^T k).tau).
STATIC_ANSATZ_GENERATORS: tuple[Generator, ...] = (
    (((-1, 0, 0), (0, -1, 0), (0, 0, 1)), (0, 0, 2)),
    (((1, 0, 0), (0, 1, 0), (0, 0, -1)), (1, 3, 0)),
    (((0, -1, 0), (-1, 0, 0), (0, 0, 1)), (1, 1, 2)),
)


# The exact two-amplitude plane supporting the higher eta=10,000 local branch.
# Its first generator is a reflection combined with a half-period y-shift; the
# second is a signed cyclic coordinate isometry. Both preserve R, E and P.
COMPETING_ANSATZ_GENERATORS: tuple[Generator, ...] = (
    (((-1, 0, 0), (0, 1, 0), (0, 0, 1)), (0, 2, 0)),
    (((0, -1, 0), (0, 0, 1), (-1, 0, 0)), (0, 0, 0)),
)

# The exact finite group generated by the preceding two transformations is
# A_4 x C_2.  These witnesses give a transparent internal direct-product
# certificate: the second element below is central, while the first together
# with the order-three ansatz generator generates the A_4 complement.
COMPETING_CENTRAL_INVOLUTION: Generator = (
    ((-1, 0, 0), (0, -1, 0), (0, 0, -1)),
    (2, 2, 2),
)
COMPETING_A4_COMPLEMENT_INVOLUTION: Generator = (
    ((-1, 0, 0), (0, -1, 0), (0, 0, 1)),
    (0, 2, 2),
)


def _transpose_apply(matrix: Matrix3, wave: tuple[int, int, int]) -> tuple[int, int, int]:
    return tuple(sum(matrix[row][column] * wave[row] for row in range(3)) for column in range(3))  # type: ignore[return-value]


def _apply_matrix(matrix: Matrix3, vector):
    return tuple(
        sum((matrix[row][column] * vector[column] for column in range(3)), QComplex())
        for row in range(3)
    )


def _matrix_multiply(left: Matrix3, right: Matrix3) -> Matrix3:
    return tuple(
        tuple(sum(left[row][index] * right[index][column] for index in range(3))
              for column in range(3))
        for row in range(3)
    )  # type: ignore[return-value]


def _matrix_vector_multiply(matrix: Matrix3, vector: tuple[int, int, int]) -> tuple[int, int, int]:
    return tuple(sum(matrix[row][column] * vector[column] for column in range(3))
                 for row in range(3))  # type: ignore[return-value]


def compose_lattice_symmetries(left: Generator, right: Generator) -> Generator:
    """Return ``left o right`` for the action ``g_(Q,m)``.

    Translation coordinates are quarter-period units and are reduced modulo
    four.  This is exact integer arithmetic, not a floating-point group
    recognition calculation.
    """

    left_matrix, left_shift = left
    right_matrix, right_shift = right
    # The stored Fourier action is
    #   g_(Q,m)^ u(k)=Q u^(Q^T k) exp(-i Q^T k . pi m/2).
    # Thus g_left o g_right has Q=Q_left Q_right and
    # m=m_right+Q_right^T m_left.  (This is the opposite shift order from a
    # naive active physical-space composition.)
    rotated_left_shift = _transpose_apply(right_matrix, left_shift)
    return (
        _matrix_multiply(left_matrix, right_matrix),
        tuple((right_shift[index] + rotated_left_shift[index]) % 4 for index in range(3)),
    )


def lattice_symmetry_order(generator: Generator) -> int:
    """Return the finite order of a listed lattice symmetry."""

    power = IDENTITY_GENERATOR
    for order in range(1, 193):  # 48 coordinate maps x 4^3 translations bounds this action.
        power = compose_lattice_symmetries(power, generator)
        if power == IDENTITY_GENERATOR:
            return order
    raise ArithmeticError("lattice symmetry order exceeded finite signed-coordinate bound")


def lattice_symmetry_group(generators: Sequence[Generator]) -> frozenset[Generator]:
    """Generate the exact finite group generated by ``generators``."""

    group: set[Generator] = {IDENTITY_GENERATOR}
    changed = True
    while changed:
        changed = False
        for left in tuple(group):
            for right in tuple(generators) + tuple(group):
                product = compose_lattice_symmetries(left, right)
                if product not in group:
                    group.add(product)
                    changed = True
    return frozenset(group)


@lru_cache(maxsize=1)
def competing_symmetry_group() -> frozenset[Generator]:
    """Return the 24 exact symmetries generated by the competing ansatz."""

    return lattice_symmetry_group(COMPETING_ANSATZ_GENERATORS)


def competing_symmetry_group_structure() -> dict[str, object]:
    """Certify from exact multiplication that the group is ``A_4 x C_2``.

    The order profile of the complement is ``1 + 3*2 + 8*3``; among groups of
    order twelve this identifies ``A_4``.  A central involution with trivial
    intersection and product covering the full 24-element group proves the
    internal direct product.
    """

    group = competing_symmetry_group()
    center = frozenset(
        element
        for element in group
        if all(
            compose_lattice_symmetries(element, other)
            == compose_lattice_symmetries(other, element)
            for other in group
        )
    )
    complement = lattice_symmetry_group(
        (COMPETING_A4_COMPLEMENT_INVOLUTION, COMPETING_ANSATZ_GENERATORS[1])
    )
    central_factor = frozenset((IDENTITY_GENERATOR, COMPETING_CENTRAL_INVOLUTION))
    product_set = frozenset(
        compose_lattice_symmetries(left, right)
        for left in complement
        for right in central_factor
    )
    profile = {
        order: sum(lattice_symmetry_order(element) == order for element in group)
        for order in (1, 2, 3, 6)
    }
    complement_profile = {
        order: sum(lattice_symmetry_order(element) == order for element in complement)
        for order in (1, 2, 3)
    }
    verified = bool(
        len(group) == 24
        and center == central_factor
        and COMPETING_CENTRAL_INVOLUTION in group
        and len(complement) == 12
        and complement_profile == {1: 1, 2: 3, 3: 8}
        and complement.isdisjoint(central_factor - {IDENTITY_GENERATOR})
        and product_set == group
    )
    return {
        "group_order": len(group),
        "order_profile": profile,
        "center_order": len(center),
        "central_involution_order": lattice_symmetry_order(COMPETING_CENTRAL_INVOLUTION),
        "a4_complement_order": len(complement),
        "a4_complement_order_profile": complement_profile,
        "direct_product_verified": verified,
        "abstract_group": "A4 x C2" if verified else None,
    }


def _zero_control_matrix() -> list[list[Fraction]]:
    return [[Fraction(0) for _ in range(64)] for _ in range(64)]


def _competing_isotypic_rank(parity: int, character: dict[int, int]) -> int:
    """Return an exact rank of an unnormalised central character projector."""

    complement = lattice_symmetry_group(
        (COMPETING_A4_COMPLEMENT_INVOLUTION, COMPETING_ANSATZ_GENERATORS[1])
    )
    accumulator = _zero_control_matrix()
    for element in complement:
        coefficient = Fraction(character[lattice_symmetry_order(element)])
        direct = static_symmetry_matrix(element)
        central_shifted = static_symmetry_matrix(
            compose_lattice_symmetries(element, COMPETING_CENTRAL_INVOLUTION)
        )
        for row in range(64):
            for column in range(64):
                accumulator[row][column] += coefficient * (
                    direct[row][column] + parity * central_shifted[row][column]
                )
    return _rank(accumulator)


@lru_cache(maxsize=1)
def competing_representation_sector_dimensions() -> dict[str, object]:
    """Give exact isotypic dimensions of the 64-control group action.

    Restricting to the $A_4$ complement, the real irreducible characters have
    values ``(1,1,1)``, ``(2,2,-1)``, and ``(3,-1,0)`` on elements of orders
    ``1,2,3`` respectively.  Combining their central projectors with the
    central $C_2$ signs gives six exact rational projectors. The ranks below
    are calculated over the rationals from the actual Fourier-control action.
    """

    characters = {
        "trivial": {1: 1, 2: 1, 3: 1},
        "two_dimensional": {1: 2, 2: 2, 3: -1},
        "three_dimensional": {1: 3, 2: -1, 3: 0},
    }
    sectors = {
        f"{name}_{'even' if parity == 1 else 'odd'}": _competing_isotypic_rank(
            parity, character
        )
        for parity in (1, -1)
        for name, character in characters.items()
    }
    expected = {
        "trivial_even": 2,
        "two_dimensional_even": 6,
        "three_dimensional_even": 24,
        "trivial_odd": 2,
        "two_dimensional_odd": 6,
        "three_dimensional_odd": 24,
    }
    return {
        "sector_dimensions": sectors,
        "sum": sum(sectors.values()),
        "exact_isotypic_decomposition_verified": sectors == expected and sum(sectors.values()) == 64,
    }


def _phase(exponent: int) -> QComplex:
    return (QComplex(1), QComplex(0, -1), QComplex(-1), QComplex(0, 1))[exponent % 4]


def transform_static_controls(
    controls: Sequence[Fraction], generator: Generator
) -> tuple[Fraction, ...]:
    """Apply one exact lattice symmetry in canonical low-mode coordinates."""

    model = StaticLowModePolynomial()
    if len(controls) != model.dimension:
        raise ValueError("expected 64 canonical controls")
    matrix, shift = generator
    field = model.exact_field(controls)
    transformed = {}
    waves = [
        signed_wave
        for wave in model.pairs
        for signed_wave in (wave, tuple(-component for component in wave))
    ]
    zero = (QComplex(), QComplex(), QComplex())
    for wave in waves:
        source_wave = _transpose_apply(matrix, wave)
        exponent = sum(source_wave[index] * shift[index] for index in range(3))
        transformed[wave] = tuple(
            _phase(exponent) * component
            for component in _apply_matrix(matrix, field.get(source_wave, zero))
        )

    output: list[Fraction] = []
    for wave in model.pairs:
        p1, p2 = integer_polarizations(wave)
        coefficient = transformed[wave]
        z1 = sum((p1[index] * coefficient[index] for index in range(3)), QComplex())
        z1 /= sum(value * value for value in p1)
        z2 = sum((p2[index] * coefficient[index] for index in range(3)), QComplex())
        z2 /= sum(value * value for value in p2)
        output.extend((z1.real, z2.real, z1.imag, z2.imag))
    return tuple(output)


def _unit(index: int) -> tuple[Fraction, ...]:
    controls = [Fraction(0)] * 64
    controls[index] = Fraction(1)
    return tuple(controls)


def signed_coordinate_matrices() -> tuple[Matrix3, ...]:
    """Return the 48 signed-permutation matrices of the cubic isometry group."""

    return tuple(
        tuple(
            tuple(signs[row] if permutation[row] == column else 0 for column in range(3))
            for row in range(3)
        )
        for permutation in permutations(range(3))
        for signs in product((-1, 1), repeat=3)
    )  # type: ignore[return-value]


@lru_cache(maxsize=None)
def static_symmetry_matrix(generator: Generator) -> tuple[tuple[Fraction, ...], ...]:
    """Return the exact 64x64 control matrix for one generator."""

    columns = [transform_static_controls(_unit(index), generator) for index in range(64)]
    return tuple(tuple(columns[column][row] for column in range(64)) for row in range(64))


def _rank(rows: Sequence[Sequence[Fraction]]) -> int:
    """Exact Gaussian-elimination rank over the rationals."""

    matrix = [list(row) for row in rows if any(row)]
    rank = 0
    column = 0
    while rank < len(matrix) and column < len(matrix[0]):
        pivot = next((row for row in range(rank, len(matrix)) if matrix[row][column]), None)
        if pivot is None:
            column += 1
            continue
        matrix[rank], matrix[pivot] = matrix[pivot], matrix[rank]
        divisor = matrix[rank][column]
        matrix[rank] = [value / divisor for value in matrix[rank]]
        for row in range(len(matrix)):
            if row != rank and matrix[row][column]:
                factor = matrix[row][column]
                matrix[row] = [
                    matrix[row][index] - factor * matrix[rank][index]
                    for index in range(len(matrix[row]))
                ]
        rank += 1
        column += 1
    return rank


def static_ansatz_fixed_space_dimension() -> int:
    """Return the exact dimension of the common fixed space of the generators."""

    rows = []
    for generator in STATIC_ANSATZ_GENERATORS:
        matrix = static_symmetry_matrix(generator)
        rows.extend(
            tuple(matrix[row][column] - Fraction(int(row == column)) for column in range(64))
            for row in range(64)
        )
    return 64 - _rank(rows)


def reduced_ansatz_is_exact_fixed_space() -> bool:
    """Verify that the six explicit embedding columns span the fixed space."""

    columns = [
        embed_reduced_static(
            tuple(Fraction(int(index == amplitude)) for index in range(6))
        )
        for amplitude in range(6)
    ]
    if _rank(tuple(zip(*columns, strict=True))) != 6:
        return False
    for generator in STATIC_ANSATZ_GENERATORS:
        matrix = static_symmetry_matrix(generator)
        for column in columns:
            image = tuple(
                sum((matrix[row][index] * column[index] for index in range(64)), Fraction(0))
                for row in range(64)
            )
            if image != column:
                return False
    return static_ansatz_fixed_space_dimension() == 6


def competing_ansatz_fixed_space_dimension() -> int:
    """Return the exact dimension fixed by the competing-branch generators."""

    rows = []
    for generator in COMPETING_ANSATZ_GENERATORS:
        matrix = static_symmetry_matrix(generator)
        rows.extend(
            tuple(
                matrix[row][column] - Fraction(int(row == column))
                for column in range(64)
            )
            for row in range(64)
        )
    return 64 - _rank(rows)


def reduced_competing_ansatz_is_exact_fixed_space() -> bool:
    """Verify that the two-amplitude embedding is the whole fixed space."""

    columns = [
        embed_competing(Fraction(int(index == 0)), Fraction(int(index == 1)))
        for index in range(2)
    ]
    if _rank(tuple(zip(*columns, strict=True))) != 2:
        return False
    for generator in COMPETING_ANSATZ_GENERATORS:
        matrix = static_symmetry_matrix(generator)
        for column in columns:
            image = tuple(
                sum(
                    (matrix[row][index] * column[index] for index in range(64)),
                    Fraction(0),
                )
                for row in range(64)
            )
            if image != column:
                return False
    return competing_ansatz_fixed_space_dimension() == 2


__all__ = [
    "COMPETING_A4_COMPLEMENT_INVOLUTION",
    "COMPETING_CENTRAL_INVOLUTION",
    "STATIC_ANSATZ_GENERATORS",
    "COMPETING_ANSATZ_GENERATORS",
    "IDENTITY_GENERATOR",
    "compose_lattice_symmetries",
    "competing_ansatz_fixed_space_dimension",
    "competing_symmetry_group",
    "competing_symmetry_group_structure",
    "competing_representation_sector_dimensions",
    "lattice_symmetry_group",
    "lattice_symmetry_order",
    "reduced_competing_ansatz_is_exact_fixed_space",
    "reduced_ansatz_is_exact_fixed_space",
    "signed_coordinate_matrices",
    "static_ansatz_fixed_space_dimension",
    "static_symmetry_matrix",
    "transform_static_controls",
]
