"""Record the exact finite symmetry group of the competing two-mode plane.

The calculation uses only integer signed-coordinate matrices and translations
modulo a quarter period.  It is therefore an exact finite group certificate,
not a numerical symmetry-recognition routine.
"""

from __future__ import annotations

import json
from hashlib import sha256
from pathlib import Path

from extreme_flows.static_symmetry import (
    COMPETING_A4_COMPLEMENT_INVOLUTION,
    COMPETING_ANSATZ_GENERATORS,
    COMPETING_CENTRAL_INVOLUTION,
    competing_symmetry_group_structure,
)


ROOT = Path(__file__).resolve().parents[1]


def _record(relative: str) -> dict[str, object]:
    path = ROOT / relative
    data = path.read_bytes()
    return {
        "path": relative.replace("\\", "/"),
        "size_bytes": len(data),
        "sha256": sha256(data).hexdigest(),
    }


def _serialize(generator):
    matrix, shift = generator
    return {"matrix": [list(row) for row in matrix], "quarter_shift": list(shift)}


def build_payload() -> dict[str, object]:
    """Build the exact group-structure record used by the manuscript."""

    structure = competing_symmetry_group_structure()
    certified = bool(structure["direct_product_verified"])
    if not certified:
        raise AssertionError("the competing symmetry group did not close as A4 x C2")
    return {
        "schema_version": 1,
        "truth_label": "exact_competing_lattice_symmetry_group_A4_times_C2",
        "statement": (
            "The exact 24-element lattice group generated by the two competing "
            "ansatz transformations is internally A4 x C2. This identifies the "
            "symmetry group only; it is not a parameter-uniform Hessian theorem."
        ),
        "generators": [_serialize(generator) for generator in COMPETING_ANSATZ_GENERATORS],
        "central_involution": _serialize(COMPETING_CENTRAL_INVOLUTION),
        "A4_complement_involution": _serialize(COMPETING_A4_COMPLEMENT_INVOLUTION),
        "exact_structure": structure,
        "checker_source": _record("scripts/certify_competing_symmetry_group.py"),
        "group_implementation": _record("src/extreme_flows/static_symmetry.py"),
        "claims": {
            "generated_group_has_order_24": structure["group_order"] == 24,
            "generated_group_is_A4_times_C2": certified,
            "parameter_uniform_full_space_local_maximum": False,
            "full_space_global_maximum": False,
        },
    }


def main() -> None:
    output = ROOT / "artifacts" / "proofs" / "competing_symmetry_group.json"
    output.write_text(json.dumps(build_payload(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
